// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleted_emails.sql

package repository

import (
	"context"
)

const getDeletedEmail = `-- name: GetDeletedEmail :one
SELECT email_hash, deleted_by, deleted_at, cooldown_until, safe_window_until, spam_count FROM deleted_emails WHERE email_hash = $1
`

func (q *Queries) GetDeletedEmail(ctx context.Context, emailHash string) (DeletedEmail, error) {
	row := q.db.QueryRow(ctx, getDeletedEmail, emailHash)
	var i DeletedEmail
	err := row.Scan(
		&i.EmailHash,
		&i.DeletedBy,
		&i.DeletedAt,
		&i.CooldownUntil,
		&i.SafeWindowUntil,
		&i.SpamCount,
	)
	return i, err
}
