// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        uuid.UUID        `json:"id"`
	UserID    uuid.UUID        `json:"user_id"`
	Token     string           `json:"token"`
	DeviceID  pgtype.Text      `json:"device_id"`
	UserAgent pgtype.Text      `json:"user_agent"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type User struct {
	UserID       uuid.UUID        `json:"user_id"`
	Username     string           `json:"username"`
	PasswordHash string           `json:"password_hash"`
	Email        pgtype.Text      `json:"email"`
	IsVerify     pgtype.Bool      `json:"is_verify"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
