// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteRefreshToken(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, userID uuid.UUID) error
	DeleteUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (RefreshToken, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
}

var _ Querier = (*Queries)(nil)
