// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addEmail = `-- name: AddEmail :exec
UPDATE users
SET email_encrypted = $1,
    email_hash = $2
WHERE user_id = $3
`

type AddEmailParams struct {
	EmailEncrypted pgtype.Text `json:"email_encrypted"`
	EmailHash      pgtype.Text `json:"email_hash"`
	UserID         uuid.UUID   `json:"user_id"`
}

func (q *Queries) AddEmail(ctx context.Context, arg AddEmailParams) error {
	_, err := q.db.Exec(ctx, addEmail, arg.EmailEncrypted, arg.EmailHash, arg.UserID)
	return err
}

const checkActiveEmail = `-- name: CheckActiveEmail :one
SELECT email_hash
FROM users
WHERE email_hash = $1
`

func (q *Queries) CheckActiveEmail(ctx context.Context, emailHash pgtype.Text) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, checkActiveEmail, emailHash)
	var email_hash pgtype.Text
	err := row.Scan(&email_hash)
	return email_hash, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, display_name, username, password_hash)
VALUES ($1, $2, $3, $4)
`

type CreateUserParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	DisplayName  pgtype.Text `json:"display_name"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.UserID,
		arg.DisplayName,
		arg.Username,
		arg.PasswordHash,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, userID)
	return err
}

const getEmail = `-- name: GetEmail :one
SELECT email_encrypted, email_hash
FROM users
WHERE user_id = $1
`

type GetEmailRow struct {
	EmailEncrypted pgtype.Text `json:"email_encrypted"`
	EmailHash      pgtype.Text `json:"email_hash"`
}

func (q *Queries) GetEmail(ctx context.Context, userID uuid.UUID) (GetEmailRow, error) {
	row := q.db.QueryRow(ctx, getEmail, userID)
	var i GetEmailRow
	err := row.Scan(&i.EmailEncrypted, &i.EmailHash)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT avatar_url, display_name, email_encrypted, is_2fa, created_at, updated_at
FROM users
WHERE user_id = $1
`

type GetProfileRow struct {
	AvatarUrl      pgtype.Text      `json:"avatar_url"`
	DisplayName    pgtype.Text      `json:"display_name"`
	EmailEncrypted pgtype.Text      `json:"email_encrypted"`
	Is2fa          pgtype.Bool      `json:"is_2fa"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) GetProfile(ctx context.Context, userID uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.AvatarUrl,
		&i.DisplayName,
		&i.EmailEncrypted,
		&i.Is2fa,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT user_id, avatar_url, display_name, username, password_hash, email_encrypted, email_hash, is_2fa, change_pass_at, created_at, updated_at FROM users
WHERE user_id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, userID uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.Username,
		&i.PasswordHash,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.Is2fa,
		&i.ChangePassAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT user_id, avatar_url, display_name, username, password_hash, email_encrypted, email_hash, is_2fa, change_pass_at, created_at, updated_at FROM users
WHERE username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.AvatarUrl,
		&i.DisplayName,
		&i.Username,
		&i.PasswordHash,
		&i.EmailEncrypted,
		&i.EmailHash,
		&i.Is2fa,
		&i.ChangePassAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeEmail = `-- name: RemoveEmail :exec
UPDATE users
SET email_encrypted = NULL,
    email_hash = NULL
WHERE user_id = $1
`

func (q *Queries) RemoveEmail(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeEmail, userID)
	return err
}

const toggle2Fa = `-- name: Toggle2Fa :exec
UPDATE users
SET is_2fa = $2, updated_at = now()
WHERE user_id = $1
`

type Toggle2FaParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Is2fa  pgtype.Bool `json:"is_2fa"`
}

func (q *Queries) Toggle2Fa(ctx context.Context, arg Toggle2FaParams) error {
	_, err := q.db.Exec(ctx, toggle2Fa, arg.UserID, arg.Is2fa)
	return err
}

const updateAvatarURL = `-- name: UpdateAvatarURL :exec
UPDATE users
SET avatar_url = $2, updated_at = now()
WHERE user_id = $1
`

type UpdateAvatarURLParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpdateAvatarURL(ctx context.Context, arg UpdateAvatarURLParams) error {
	_, err := q.db.Exec(ctx, updateAvatarURL, arg.UserID, arg.AvatarUrl)
	return err
}

const updateDisplayName = `-- name: UpdateDisplayName :exec
UPDATE users
SET display_name = $2, updated_at = now()
WHERE user_id = $1
`

type UpdateDisplayNameParams struct {
	UserID      uuid.UUID   `json:"user_id"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) error {
	_, err := q.db.Exec(ctx, updateDisplayName, arg.UserID, arg.DisplayName)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2, updated_at = now(), change_pass_at = now()
WHERE user_id = $1
`

type UpdatePasswordParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.UserID, arg.PasswordHash)
	return err
}
