#!/bin/bash
set -e


for file in proto/*.proto; do
  
  fname=$(basename "$file" .proto)

  outdir="proto/gen/$fname"
  mkdir -p "$outdir"

  echo ">> Generating code for $file into $outdir"

  protoc \
    --go_out="$outdir" \
    --go-grpc_out="$outdir" \
    --go_opt=paths=source_relative \
    --go-grpc_opt=paths=source_relative \
    "$file"
done
