// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artist_songs.sql

package repository

import (
	"context"
)

const addSongArtists = `-- name: AddSongArtists :exec
INSERT INTO artist_songs (artist_id, song_id)
VALUES ($1, $2)
`

type AddSongArtistsParams struct {
	ArtistID int32  `json:"artist_id"`
	SongID   string `json:"song_id"`
}

func (q *Queries) AddSongArtists(ctx context.Context, arg AddSongArtistsParams) error {
	_, err := q.db.Exec(ctx, addSongArtists, arg.ArtistID, arg.SongID)
	return err
}

const removeSongArtists = `-- name: RemoveSongArtists :exec
DELETE FROM artist_songs
WHERE song_id = $1
`

func (q *Queries) RemoveSongArtists(ctx context.Context, songID string) error {
	_, err := q.db.Exec(ctx, removeSongArtists, songID)
	return err
}
