// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Artist struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type ArtistSong struct {
	ArtistID int32  `json:"artist_id"`
	SongID   string `json:"song_id"`
}

type Playlist struct {
	PlaylistID   uuid.UUID        `json:"playlist_id"`
	PlaylistName pgtype.Text      `json:"playlist_name"`
	OwnerID      uuid.UUID        `json:"owner_id"`
	IsPublic     pgtype.Bool      `json:"is_public"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type PlaylistSong struct {
	SongID     string    `json:"song_id"`
	PlaylistID uuid.UUID `json:"playlist_id"`
	Position   int32     `json:"position"`
}

type Song struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	TitleToken []string `json:"title_token"`
	Categories []string `json:"categories"`
}
