// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: playlist_song.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const addSongToPlaylist = `-- name: AddSongToPlaylist :exec
INSERT INTO playlist_song (playlist_id, song_id, position)
VALUES ($1, $2, $3)
`

type AddSongToPlaylistParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     string    `json:"song_id"`
	Position   int32     `json:"position"`
}

func (q *Queries) AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error {
	_, err := q.db.Exec(ctx, addSongToPlaylist, arg.PlaylistID, arg.SongID, arg.Position)
	return err
}

const removeSongFromPlaylist = `-- name: RemoveSongFromPlaylist :exec
DELETE FROM playlist_song
WHERE playlist_id = $1 AND song_id = $2
`

type RemoveSongFromPlaylistParams struct {
	PlaylistID uuid.UUID `json:"playlist_id"`
	SongID     string    `json:"song_id"`
}

func (q *Queries) RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error {
	_, err := q.db.Exec(ctx, removeSongFromPlaylist, arg.PlaylistID, arg.SongID)
	return err
}
