// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddSongArtists(ctx context.Context, arg AddSongArtistsParams) error
	AddSongToPlaylist(ctx context.Context, arg AddSongToPlaylistParams) error
	CreateArtist(ctx context.Context, name string) (Artist, error)
	CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (Song, error)
	DeleteArtist(ctx context.Context, id int32) error
	DeletePlaylist(ctx context.Context, playlistID uuid.UUID) error
	DeleteSong(ctx context.Context, id string) error
	GetArtistById(ctx context.Context, id int32) (Artist, error)
	GetPlaylistById(ctx context.Context, playlistID uuid.UUID) (Playlist, error)
	GetSongById(ctx context.Context, id string) (Song, error)
	ListArtists(ctx context.Context, arg ListArtistsParams) ([]Artist, error)
	ListPlaylists(ctx context.Context, arg ListPlaylistsParams) ([]Playlist, error)
	ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error)
	ListSongsWithArtists(ctx context.Context, arg ListSongsWithArtistsParams) ([]ListSongsWithArtistsRow, error)
	RemoveSongArtists(ctx context.Context, songID string) error
	RemoveSongFromPlaylist(ctx context.Context, arg RemoveSongFromPlaylistParams) error
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) (Artist, error)
	UpdatePlaylist(ctx context.Context, arg UpdatePlaylistParams) (Playlist, error)
	UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error)
}

var _ Querier = (*Queries)(nil)
