// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: songs.sql

package repository

import (
	"context"
)

const createSong = `-- name: CreateSong :one
INSERT INTO songs (id, title, title_token, categories)
VALUES ($1, $2, $3, $4)
RETURNING id, title, title_token, categories
`

type CreateSongParams struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	TitleToken []string `json:"title_token"`
	Categories []string `json:"categories"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.ID,
		arg.Title,
		arg.TitleToken,
		arg.Categories,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleToken,
		&i.Categories,
	)
	return i, err
}

const deleteSong = `-- name: DeleteSong :exec
DELETE FROM songs
WHERE id = $1
`

func (q *Queries) DeleteSong(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSong, id)
	return err
}

const getSongById = `-- name: GetSongById :one
SELECT id, title, title_token, categories
FROM songs
WHERE id = $1
`

func (q *Queries) GetSongById(ctx context.Context, id string) (Song, error) {
	row := q.db.QueryRow(ctx, getSongById, id)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleToken,
		&i.Categories,
	)
	return i, err
}

const listSongs = `-- name: ListSongs :many
SELECT id, title, title_token, categories
FROM songs
ORDER BY id
LIMIT $1 OFFSET $2
`

type ListSongsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSongs(ctx context.Context, arg ListSongsParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Song{}
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleToken,
			&i.Categories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsWithArtists = `-- name: ListSongsWithArtists :many
SELECT 
    s.id, 
    s.title, 
    s.title_token, 
    s.categories,
    COALESCE(
        json_agg(json_build_object('id', a.id, 'name', a.name)) 
        FILTER (WHERE a.id IS NOT NULL),
        '[]'
    ) AS artists
FROM 
    songs s
LEFT JOIN 
    artist_songs sa ON sa.song_id = s.id
LEFT JOIN 
    artists a ON a.id = sa.artist_id
GROUP BY 
    s.id, s.title, s.title_token, s.categories
ORDER BY 
    s.id
LIMIT $1 OFFSET $2
`

type ListSongsWithArtistsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSongsWithArtistsRow struct {
	ID         string      `json:"id"`
	Title      string      `json:"title"`
	TitleToken []string    `json:"title_token"`
	Categories []string    `json:"categories"`
	Artists    interface{} `json:"artists"`
}

func (q *Queries) ListSongsWithArtists(ctx context.Context, arg ListSongsWithArtistsParams) ([]ListSongsWithArtistsRow, error) {
	rows, err := q.db.Query(ctx, listSongsWithArtists, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSongsWithArtistsRow{}
	for rows.Next() {
		var i ListSongsWithArtistsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleToken,
			&i.Categories,
			&i.Artists,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET title = $2, title_token = $3, categories = $4
WHERE id = $1
RETURNING id, title, title_token, categories
`

type UpdateSongParams struct {
	ID         string   `json:"id"`
	Title      string   `json:"title"`
	TitleToken []string `json:"title_token"`
	Categories []string `json:"categories"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, updateSong,
		arg.ID,
		arg.Title,
		arg.TitleToken,
		arg.Categories,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleToken,
		&i.Categories,
	)
	return i, err
}
